/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <ctype.h>


void calcprog_1(char *host, double a, char op, double b, double * result)
{
	CLIENT *clnt;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCPROG, CALCVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	switch (op)
	{
		case '+':
			*result = *add_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case '-':
			*result = *sub_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case 'x':
			*result = *mul_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case '/':
			if(b == 0){
				printf("AVISO: Estas dividiendo por 0\n");
			}
			*result = *div_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;
		
		default:
			printf("Operación errónea\n");
		break;
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

}

void calcprog_2(char * host, t_vec a, t_vec b, double c, char op){
	CLIENT *clnt;
	double * e;
	t_vec * result;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCPROG, CALCVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	switch (op)
	{
		case '1':
			result = addv_1(a,b,clnt);
			if(result == (t_vec *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case '2':
			result = subv_1(a,b,clnt);
			if(result == (t_vec *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;
		
		case '3':
			e = dot_1(a,b,clnt);
			if(e == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case '4':
			result = cross_1(a,b,clnt);
			if(result == (t_vec *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;

		case '5':
			result = mulv_1(a,c,clnt);
			if(result == (t_vec *) NULL){
				clnt_perror (clnt, "call failed");
			}
		break;
	}

	if(op == '3'){
		printf("El resultado de la operación es: %f\n", *e);
	}
	else{
		printf("El vector resultado es: (");
		for(int i = 0; i < 2; i++){
			printf("%f,",result->t_vec_val[i]);
		}
		printf("%f)\n",result->t_vec_val[2]);
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

void numberMode(int argc, char *argv[]){
	char *host;
	host = argv[1];

	int size = (argc-3)/2;
	char * end;

	double operands[size+1];
	char operators[size];
	double result;

	int j = 0;

	for(int i = 3; i < argc-1; i+=2){
		operands[j] = strtod(argv[i], &end);
		if(*end != '\0'){
			printf("Alguno de los operandos introducidos no es un número\n");
			exit(-1);
		}
		operators[j] = argv[i+1][0];
		j++;
	}
	operands[size] = strtod(argv[argc-1], &end);
	if(*end != '\0'){
		printf("Alguno de los operandos introducidos no es un número\n");
		exit(-1);
	}

	calcprog_1(host,operands[0],operators[0],operands[1],&result);

	for(int i = 1; i < size; i++){
		calcprog_1(host,result,operators[i],operands[i+1],&result);
	}

	printf("Resultado de la operación: %f\n", result);
}

t_vec readVector(){
	t_vec vector;
	vector.t_vec_len = 3;
	vector.t_vec_val = (double *)malloc(3*sizeof(double));

	char elements[10];
	double ele;
	int reads = 0;
	do{
		fgets(elements,10,stdin);
		if(sscanf(elements,"%lf",&ele) == 0){
			printf("El elemento introducido no es un número válido\n");
		}
		else{
			vector.t_vec_val[reads] = ele;
			reads++;
		}
	}while(reads < 3);

	return vector;
}

void vectorMode(char * host){
	printf("Selecciona la operación a realizar:\n1-Sumar\n2-Restar\n3-Producto Escalar\n4-Producto Vectorial\n5-Producto por un escalar\n");
	char option[3];
	t_vec vecA, vecB;
	double e;
	int valid = 0;

	while(!valid){
		valid = 1;
		fgets(option,3,stdin);
		switch (option[0])
		{
			case '1':

			case '2':

			case '3':

			case '4':
				printf("Introduce los elementos del primer vector\n");
				vecA = readVector();
				printf("Introduce los elementos del segundo vector\n");
				vecB = readVector();
			break;

			case '5':
				printf("Introduce los elementos del vector\n");
				vecA = readVector();
				printf("Introduce el escalar\n");
				char elements[10];
				while(1){
					fgets(elements,10,stdin);
					if(sscanf(elements,"%lf",&e) == 0){
						printf("El elemento introducido no es un número válido\n");
					}
					else{
						break;
					}
				}
			break;
			
			default:
				printf("Opción inválida\n");
				valid = 0;
			break;
		}
	}

	calcprog_2(host, vecA, vecB, e, option[0]);
}

int main (int argc, char *argv[])
{
	if(argc > 2 && argv[2][0] == 'n'){
		if (argc < 5){
			printf("Uso: <host> <modo> <número> <operación> <número> <operación> <número> ...\n");
			exit(-1);
		}
		else if (argc % 2 != 0){
			printf("Uso: <host> <modo> <número> <operación> <número> <operación> <número> ...\n");
			exit(-1);
		}
		numberMode(argc,argv);
	}
	else if(argc > 2 && argv[2][0] == 'v'){
		char * host;
		host = argv[1];
		vectorMode(host);
	}
	else{
		printf("Uso: <host> <modo> <parametros>\n");
	}

	exit (0);
}