/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void calcprog_1(char *host, double a, char op, double b)
{
	CLIENT *clnt;
	double  *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCPROG, CALCVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	switch (op)
	{
		case '+':
			result = add_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
			else{
				printf("El resultado de la suma es: %f\n", *result);
			}
		break;

		case '-':
			result = sub_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
			else{
				printf("El resultado de la resta es: %f\n", *result);
			}
		break;

		case 'x':
			result = mul_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
			else{
				printf("El resultado de la multiplicación es: %f\n", *result);
			}
		break;

		case '/':
			if(b == 0){
				printf("AVISO: Estas dividiendo por 0\n");
			}
			result = div_1(a,b,clnt);
			if(result == (double *) NULL){
				clnt_perror (clnt, "call failed");
			}
			else{
				printf("El resultado de la división es: %f\n", *result);
			}
		break;
		
		default:
			printf("Operación errónea\n");
		break;
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 5){
		printf("Uso: <host> <número> <operación> <número>\n");
		exit(-1);
	}

	double num1, num2;
	char op;
	char * end;

	num1 = strtod(argv[2], &end);
	if(*end != '\0'){
		printf("El primer operando introducido no es un número\n");
		exit(-1);
	}

	num2 = strtod(argv[4], &end);
	if(*end != '\0'){
		printf("El segundo operando introducido no es un número\n");
		exit(-1);
	}

	op = argv[3][0];

	host = argv[1];

	calcprog_1(host,num1,op,num2);
	exit (0);
}
